### ISSUE TITLE
cli tool: download in tmpdir vs /tmp

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/osf-packaging#6]
[Originally](https://github.com/DataConservancy/dcs-packaging-tool/issues/18) from @msuhovec:

> It appears that the current version of the cli package download downloads all of its files into /tmp
on the calling machine. For single-threaded exection, this is fine; however, for multithreaded execution, it is possible to overwrite another session's download, or cause it to fail if downloads are run under different user ids.

> One possible solution to this is use a utility like Files.createTempDirectory, giving each session its own unique temp directory for downloads.

**Comment by emetsger** [comment]
@msuhovec: this should be fixed in the latest build, please give it a try and if fixed, close this issue!  Thanks!

**Comment by msuhovec** [comment]
This has been fixed in the 10/19 osf-cli-1.0.2-20161019.155901-4.jar version of the tool.

**Comment by msuhovec** [comment]
Elliot- I don't seem to have the priv to close this- could you?

**Comment by emetsger** [comment]
@msuhovec of course! probably because I created it... thanks for testing!
