### ISSUE TITLE
cli tool and private registrations

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/osf-packaging#8]
[Originally](https://github.com/DataConservancy/dcs-packaging-tool/issues/16) from @msuhovec:

> 
> Currently only publicly available registrations are available when used the cli tool to download packages (I guess this is expected behavior, as it is using the public API).
> 
> At some future point, we would like to be able to download private registrations and projects, using the CurateND OSF login credentials.
> 
> I guess this is an enhancement request.

**Comment by emetsger** [comment]
The client was not respecting the authorization credentials configured by the user.  This has been fixed.  The error message emitted by the CLI when a url cannot be retrieved has been improved to include the HTTP response code and status message.

**Comment by emetsger** [comment]
@msuhovec can you try the latest build of the cli (SNAPSHOTS have been deployed) and confirm that this issue has been fixed?

**Comment by msuhovec** [comment]
I'll download it and give it a try.

**Comment by msuhovec** [comment]
This works using the 10/17/16 version 1.0.2 of the cli tool.
